"""CLI tool to review uncommitted local changes using Ollama.

Compares the current working directory (including uncommitted changes)
against the target branch (default: main) and generates a markdown report
with the Ollama review.
"""

from __future__ import annotations

import argparse
import datetime
import subprocess
import sys
from pathlib import Path

# Add .github/scripts (for review_common) and the local lib/ dir (for
# ollama_common) to sys.path so this works both as an importable module and
# when invoked directly (e.g. `python scripts/developer_tools/e_local_review.py`),
# where the repo root is not on sys.path and `scripts` is not importable.
sys.path.insert(0, str(Path(__file__).parent.parent.parent / ".github" / "scripts"))
sys.path.insert(0, str(Path(__file__).parent / "lib"))
from ollama_common import (
    fetch_ollama_review,
    get_ollama_endpoint,
    get_ollama_model,
    validate_ollama_connection,
)
from review_common import build_prompt, truncate_diff


def get_git_root() -> str:
    """Get the root directory of the git repository."""
    try:
        result = subprocess.run(
            ["git", "rev-parse", "--show-toplevel"],
            capture_output=True,
            text=True,
            check=True,
        )
        return result.stdout.strip()
    except subprocess.CalledProcessError as exc:
        print(f"ERROR: Not a git repository or git command failed: {exc}", file=sys.stderr)
        raise SystemExit(1) from exc


def get_current_branch() -> str:
    """Get the current branch name."""
    try:
        result = subprocess.run(
            ["git", "rev-parse", "--abbrev-ref", "HEAD"],
            capture_output=True,
            text=True,
            check=True,
        )
        return result.stdout.strip()
    except subprocess.CalledProcessError as exc:
        print(f"ERROR: Failed to get current branch: {exc}", file=sys.stderr)
        raise SystemExit(1) from exc


def get_local_diff(target_branch: str = "main") -> str:
    """Get diff of uncommitted changes against target branch.

    Includes:
    1. Changes staged for commit
    2. Unstaged changes in tracked files
    3. Summary of untracked files (without content to avoid noise)
    """
    try:
        # Get the diff against the target branch (commits + uncommitted changes)
        result = subprocess.run(
            ["git", "diff", f"{target_branch}...HEAD"],
            capture_output=True,
            text=True,
            check=True,
        )
        diff = result.stdout

        # Also include any uncommitted changes in the working tree
        result = subprocess.run(
            ["git", "diff", "HEAD"],
            capture_output=True,
            text=True,
            check=True,
        )
        if result.stdout:
            diff += "\n" + result.stdout

        # Note untracked files
        result = subprocess.run(
            ["git", "ls-files", "--others", "--exclude-standard"],
            capture_output=True,
            text=True,
            check=True,
        )
        untracked = result.stdout.strip()
        if untracked:
            untracked_list = "\n".join(f"  {line}" for line in untracked.splitlines())
            diff += f"\n\n# Untracked files (not included in diff):\n{untracked_list}\n"

        return diff
    except subprocess.CalledProcessError as exc:
        print(f"ERROR: Failed to generate diff: {exc}", file=sys.stderr)
        raise SystemExit(1) from exc


def generate_markdown_report(
    review: str,
    target_branch: str,
    current_branch: str,
    model: str,
    diff_size: int,
    timestamp: str,
) -> str:
    """Generate a markdown report with review results."""
    return f"""# Local Code Review Report

**Generated:** {timestamp}

## Context

- **Current branch:** {current_branch}
- **Compared against:** {target_branch}
- **AI Model:** {model}
- **Diff size:** {diff_size} characters

## Review

{review}

---
*Generated by `scripts/dev_tools/local_review.py`*
"""


def save_report(content: str, output_path: str) -> str:
    """Save markdown report to file. Return the absolute path."""
    output_file = Path(output_path)
    output_file.parent.mkdir(parents=True, exist_ok=True)
    output_file.write_text(content, encoding="utf-8")
    return str(output_file.absolute())


def main() -> int:
    """Run the local review flow."""
    parser = argparse.ArgumentParser(
        description="Review uncommitted local changes using Ollama and generate a markdown report"
    )
    parser.add_argument(
        "--branch",
        default="main",
        help="Target branch to compare against (default: main)",
    )
    parser.add_argument(
        "--output",
        "-o",
        help="Output markdown file path (default: local_review_<timestamp>.md)",
    )
    parser.add_argument(
        "--stdout",
        action="store_true",
        help="Print review to stdout instead of saving to file",
    )
    args = parser.parse_args()

    # Validate Ollama is reachable
    endpoint = get_ollama_endpoint()
    if not validate_ollama_connection(endpoint):
        print(
            f"ERROR: Ollama is not reachable at {endpoint}. "
            "Please start Ollama or set OLLAMA_ENDPOINT.",
            file=sys.stderr,
        )
        return 1

    model = get_ollama_model()
    current_branch = get_current_branch()

    # Get local diff
    print(f"INFO: Comparing {current_branch} against {args.branch}...", file=sys.stderr)
    diff = get_local_diff(args.branch)

    # Truncate diff if needed
    original_diff_len = len(diff)
    diff, was_truncated = truncate_diff(diff)
    if was_truncated:
        print(
            f"INFO: Truncated diff from {original_diff_len} to {len(diff)} characters",
            file=sys.stderr,
        )

    if not diff.strip():
        print("No changes found to review.", file=sys.stderr)
        return 0

    # Build prompt and fetch review
    print(f"INFO: Using Ollama model '{model}'", file=sys.stderr)
    prompt = build_prompt(
        pr_title=f"Local changes on {current_branch}",
        diff=diff,
        issue_body="Local code review (no linked issue)",
        discussion="",
        verified_facts="",
    )
    review = fetch_ollama_review(endpoint, model, prompt)

    if not review.strip():
        print("ERROR: Ollama returned an empty review", file=sys.stderr)
        return 1

    # Generate timestamp for report
    timestamp = datetime.datetime.now(datetime.UTC).isoformat()

    # Generate markdown report
    report = generate_markdown_report(
        review=review,
        target_branch=args.branch,
        current_branch=current_branch,
        model=model,
        diff_size=len(diff),
        timestamp=timestamp,
    )

    # Output or save report
    if args.stdout:
        print(report)
        return 0
    else:
        # Determine output file path
        if args.output:
            output_path = args.output
        else:
            # Generate default filename with timestamp
            ts = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
            output_path = f"local_review_{ts}.md"

        try:
            abs_path = save_report(report, output_path)
            print(f"Review saved to: {abs_path}", file=sys.stderr)
            return 0
        except OSError as exc:
            print(f"ERROR: Failed to save report: {exc}", file=sys.stderr)
            return 1


if __name__ == "__main__":
    raise SystemExit(main())
